[project]
name = "autoparsing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "metadata-utils",
    "neurokaraoke-scraper",
    "thefuzz>=0.22.1",
]

[tool.uv.sources]
neurokaraoke-scraper = { path = "../Neurokaraoke_Scraper", editable = true }
metadata-utils = { path = "../Metadata_Utils", editable = true }
