[project]
name = "metadata_utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nyss", email = "straussnycolas@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "hjson>=3.1.0",
    "mutagen>=1.47.0",
    "pytest>=9.0.2",
    "tinytag>=2.2.0",
    "xxhash>=3.6.0",
]

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[tool.hatch.build.targets.wheel]
packages = ["src/metadata_utils"]
